version: '3.4'
services:

  torch:
    build:
      context: .
      args:
        #BASE_IMAGE: nvidia/cuda:12.0.1-runtime-ubuntu22.04
        #BASE_IMAGE: nvidia/cuda:11.1.1-runtime-ubuntu20.04
        BASE_IMAGE: ubuntu:20.04
    container_name: torch
    tty: true
    volumes:
      - .:/home/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

